/*
 *  Delta programming language
 */

#include "delta/delta.h"


DELTA_FUNCTION(abs);
DELTA_FUNCTION(acos);
DELTA_FUNCTION(acosh);
DELTA_FUNCTION(asin);
DELTA_FUNCTION(asinh);
DELTA_FUNCTION(atan);
DELTA_FUNCTION(atan2);
DELTA_FUNCTION(atanh);
DELTA_FUNCTION(cos);
DELTA_FUNCTION(sin);
DELTA_FUNCTION(sqrt);
DELTA_FUNCTION(tan);
DELTA_FUNCTION(ceil);
DELTA_FUNCTION(floor);
DELTA_FUNCTION(exp);
DELTA_FUNCTION(log);
DELTA_FUNCTION(pi);
DELTA_FUNCTION(log10);
DELTA_FUNCTION(pow);
DELTA_FUNCTION(hypot);
DELTA_FUNCTION(deg2rad);
DELTA_FUNCTION(rad2deg);
DELTA_FUNCTION(srand);
DELTA_FUNCTION(rand);
DELTA_FUNCTION(sinh);
DELTA_FUNCTION(cosh);
DELTA_FUNCTION(tanh);
DELTA_FUNCTION(getrandmax);
DELTA_FUNCTION(min);
DELTA_FUNCTION(max);
DELTA_FUNCTION(mt_getrandmax);
DELTA_FUNCTION(mt_srand);
DELTA_FUNCTION(mt_rand);
DELTA_FUNCTION(expm1);
DELTA_FUNCTION(log1p);
DELTA_FUNCTION(fmod);
DELTA_FUNCTION(lcg_value);
DELTA_FUNCTION(base_convert);
DELTA_FUNCTION(bindec);
DELTA_FUNCTION(decbin);
DELTA_FUNCTION(dechex);
DELTA_FUNCTION(decoct);
DELTA_FUNCTION(hexdec);
DELTA_FUNCTION(octdec);
